image: golang:1.12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /go/pkg/mod

before_script:
  - go mod download

stages:
  - test

format:
  stage: test
  script:
    - make test-fmt

unit:
  stage: test
  script:
    - make test-unit

# check that all mocks are checked-in and can be properly re-generated
mocks:
  stage: test
  script:
    - find . -name '*_mock.go' -delete && make mocks && test -z "$(git status --porcelain pkg)"

# a one liner that checks that there is no occurence of "okn" in any version controlled file or in
# any filepath. We exclude the go.sum from the first check since we got "unlucky" and one of the
# checksums includes "okN".
okn-rename:
  stage: test
  script:
    - ! git grep -q -i okn -- './*' ':!go.sum' && ! git ls-files | grep -i -q okn
